version: '3.7'
services:
 web:
  container_name: "flask"
  build: .
  ports:
   - "5000:5000"
  depends_on:
   - mongodb
  volumes:
   - .:/app
  environment:
   - FLASK_ENV=development # debug mode
   - PORT=5000
   - DB=mongodb://mongodb:27017/test
 mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
   - MONGO_DATA_DIR=/usr/data/testdb
   - MONGO_LOG_DIR=/dev/null
  volumes:
   - ./data/testdb:/usr/data/testdb
  ports:
   - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null --port 27017 --bind_ip_all
networks:
 default:
  name: web
